services:
  dc1:
    image: samba:almalinux
    restart: unless-stopped
    network_mode: host
    build:
      context: .
      dockerfile: dockerfiles/almalinux
    container_name: dc1
    hostname: DC1
    privileged: true
    environment:
      REALM: DGS.NET
      DOMAIN: DGS
      ADMIN_PASS: Passw0rd
      DNS_FORWARDER: 8.8.8.8
    volumes:
      - dc1_etc:/usr/local/samba/etc
      - dc1_private:/usr/local/samba/private
      - dc1_var:/usr/local/samba/var

volumes:
  dc1_etc:
  dc1_private:
  dc1_var: