services:
  dc1:
    image: samba:almalinux
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfiles/almalinux
    container_name: dc1
    hostname: DC1
    privileged: true
    environment:
      REALM: DGS.NET
      DOMAIN: DGS
      ADMIN_PASS: Passw0rd
      DNS_FORWARDER: 8.8.8.8
      BIND_NETWORK_INTERFACES: false
    dns_search: dgs.net
    dns:
      - 172.16.238.10
      - 172.16.238.20
      - 172.16.238.30
      - 172.16.238.40
    extra_hosts:
      - "DC1 DC1.dgs.net:172.16.238.10"
      - "DC2 DC2.dgs.net:172.16.238.20"
      - "DC3 DC3.dgs.net:172.16.238.30"
      - "DC4 DC4.dgs.net:172.16.238.40"
    command: ["/bin/bash", "-c", "samba-domain-provision && samba -F"]
    volumes:
      - dc1_etc:/usr/local/samba/etc
      - dc1_private:/usr/local/samba/private
      - dc1_var:/usr/local/samba/var

    networks:
      static-network:
        ipv4_address: 172.16.238.10

  dc2:
    image: samba:ubuntu
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfiles/ubuntu
    container_name: dc2
    hostname: DC2
    privileged: true
    environment:
      REALM: DGS.NET
      DOMAIN: DGS
      ADMIN_PASS: Passw0rd
      DNS_FORWARDER: 8.8.8.8
      BIND_NETWORK_INTERFACES: false
    dns_search: dgs.net
    dns:
      - 172.16.238.20
      - 172.16.238.30
      - 172.16.238.40
      - 172.16.238.10
    extra_hosts:
      - "DC1 DC1.dgs.net:172.16.238.10"
      - "DC2 DC2.dgs.net:172.16.238.20"
      - "DC3 DC3.dgs.net:172.16.238.30"
      - "DC4 DC4.dgs.net:172.16.238.40"
    command: ["/bin/bash", "-c", "samba-domain-join DC1 && samba -F"]
    volumes:
      - dc2_etc:/usr/local/samba/etc
      - dc2_private:/usr/local/samba/private
      - dc2_var:/usr/local/samba/var
    networks:
      static-network:
        ipv4_address: 172.16.238.20

  dc3:
    image: samba:rockylinux
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfiles/rockylinux
    container_name: dc3
    hostname: DC3
    privileged: true
    environment:
      REALM: DGS.NET
      DOMAIN: DGS
      ADMIN_PASS: Passw0rd
      DNS_FORWARDER: 8.8.8.8
      BIND_NETWORK_INTERFACES: false
    dns_search: dgs.net
    dns:
      - 172.16.238.30
      - 172.16.238.40
      - 172.16.238.10
      - 172.16.238.20
    extra_hosts:
      - "DC1 DC1.dgs.net:172.16.238.10"
      - "DC2 DC2.dgs.net:172.16.238.20"
      - "DC3 DC3.dgs.net:172.16.238.30"
      - "DC4 DC4.dgs.net:172.16.238.40"
    command: ["/bin/bash", "-c", "samba-domain-join DC1 && samba -F"]
    volumes:
      - dc3_etc:/usr/local/samba/etc
      - dc3_private:/usr/local/samba/private
      - dc3_var:/usr/local/samba/var
    networks:
      static-network:
        ipv4_address: 172.16.238.30

  dc4:
    image: samba:debian
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfiles/debian
    container_name: dc4
    hostname: DC4
    privileged: true
    environment:
      REALM: DGS.NET
      DOMAIN: DGS
      ADMIN_PASS: Passw0rd
      DNS_FORWARDER: 8.8.8.8
      BIND_NETWORK_INTERFACES: false
    dns_search: dgs.net
    dns:
      - 172.16.238.40
      - 172.16.238.10
      - 172.16.238.20
      - 172.16.238.30
    extra_hosts:
      - "DC1 DC1.dgs.net:172.16.238.10"
      - "DC2 DC2.dgs.net:172.16.238.20"
      - "DC3 DC3.dgs.net:172.16.238.30"
      - "DC4 DC4.dgs.net:172.16.238.40"
    command: ["/bin/bash", "-c", "samba-domain-join DC1 && samba -F"]
    volumes:
      - dc4_etc:/usr/local/samba/etc
      - dc4_private:/usr/local/samba/private
      - dc4_var:/usr/local/samba/var
    networks:
      static-network:
        ipv4_address: 172.16.238.40

volumes:
  dc1_etc:
  dc1_private:
  dc1_var:
  dc2_etc:
  dc2_private:
  dc2_var:
  dc3_etc:
  dc3_private:
  dc3_var:
  dc4_etc:
  dc4_private:
  dc4_var:


networks:
  static-network:
    ipam:
      config:
        - subnet: 172.16.238.0/24
