name: almalinux

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - "dev/**"
      - "docker-compose.yml"
      - "dc1.yml"
      - "LICENSE"
      - "Makefile"
      - "README.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Download latest samba tar file
        run: curl -o samba.tar.gz https://download.samba.org/pub/samba/samba-latest.tar.gz

      - name: Build the Docker image
        run: docker build . --file dockerfiles/almalinux --tag samba-almalinux
